### ISSUE TITLE
too optimistic line removal in error state

### ISSUE THREAD

**Issue by haraldschilly** [sharelatex/latex-log-parser-sharelatex#5]
when in state error, there is a [look ahead for empty lines](https://github.com/sharelatex/latex-log-parser-sharelatex/blob/master/src/coffee/latex-log-parser.coffee#L105). from what I see in my logfiles, there are no  such lines and therefore consecutive errors are ignored.

example output compiled via `latexmk -pdf -f -g -bibtex -synctex=1 -interaction=nonstopmode 'normal.tex'`

latex snippet

```
test

error \xtextit{te} text error

ok

\textbbf{bold}
```

gives this log snippet

```
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./normal.aux)
! Undefined control sequence.
l.9 error \xtextit
                  {te} text error
! Undefined control sequence.
l.13 \textbbf
             {bold}
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./normal.aux) )
```

and therefore I'm suggesting to just remove those two `@log.linesUpToNextWhitespaceLine()` look aheads...

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
