### ISSUE TITLE
[feature] Report missing characters

### ISSUE THREAD

**Issue by ti-s** [sharelatex/latex-log-parser-sharelatex#6]
When using lualatex, messages about missing characters are written to the log file. It would be helpful, if these messages were parsed and reported similar to warnings, so that they are not accidentally ignored.

Minimal example:
```
\documentclass{article}
\usepackage{fontspec}
\begin{document}
$1 µm$ % results in 1m
\end{document}
```
In the log file:
`Missing character: There is no µ (U+00B5) in font cmmi10!`

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
