### ISSUE TITLE
Support `\ClassWarning`

### ISSUE THREAD

**Issue by adamsmd** [sharelatex/latex-log-parser-sharelatex#9]
The current regex for warnings in `latex-log-parser` covers package warnings generated from `\PackageWarning` (e.g., "Package balance Warning: You have ...") but not class warnings generated from `\ClassWarning` (and `\ClassWarningNoLine`) (e.g., "Class beamer Warning: This option is obsolete. Use ...").

Would it be possible to add support for `\ClassWarning`?

For reference, it looks like errors and warnings can be generated from the following commands defined in `/usr/share/texlive/texmf-dist/tex/latex/base/latex.ltx`:
- `\PackageError`
- `\PackageWarning`
- `\PackageWarningNoLine`
- `\PackageInfo`
- `\ClassError`
- `\ClassWarning`
- `\ClassWarningNoLine`
- `\@latex@error`
- `\@latex@warning`
- `\@latex@warning@no@line`
- `\@latex@info`
- `\@latex@info@no@line`

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
